name = "nile-soniq-auth"
main = "worker.js"
compatibility_date = "2026-10-05"

[[d1_databases]]
binding = "DB"
database_name = "nilesoniq"
database_id = "448a8c6f-eb5c-4a34-b804-2dc47255a05a"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "nilesoniq-media"

[assets]
directory = "public"
binding = "ASSETS"
